// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: payService.proto

package payrpc

import (
	"context"

	"zero-qp/payService/rpc/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pay.Request
	Response = pay.Response

	PayRPC interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPayRPC struct {
		cli zrpc.Client
	}
)

func NewPayRPC(cli zrpc.Client) PayRPC {
	return &defaultPayRPC{
		cli: cli,
	}
}

func (m *defaultPayRPC) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pay.NewPayRPCClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
