// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type RegisterReq struct {
	Account       string `json:"account,omitempty"`
	Password      string `json:"password,omitempty"`
	LoginPlatform int32  `json:"loginPlatform,omitempty"`
}

type RegisterResp struct {
	ServerInfo ServerInfo `json:"serverInfo"`
	Token      string     `json:"token"`
}

type ServerInfo struct {
	Host string `json:"host"`
	Port int32  `json:"port"`
}
