// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: payService.proto

package server

import (
	"context"

	"zero-qp/payService/rpc/internal/logic"
	"zero-qp/payService/rpc/internal/svc"
	"zero-qp/payService/rpc/pay"
)

type PayRPCServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPayRPCServer
}

func NewPayRPCServer(svcCtx *svc.ServiceContext) *PayRPCServer {
	return &PayRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *PayRPCServer) Ping(ctx context.Context, in *pay.Request) (*pay.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
