// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: gameService.proto

package server

import (
	"context"

	"zero-qp/gameService/rpc/game"
	"zero-qp/gameService/rpc/internal/logic"
	"zero-qp/gameService/rpc/internal/svc"
)

type GameRPCServer struct {
	svcCtx *svc.ServiceContext
	game.UnimplementedGameRPCServer
}

func NewGameRPCServer(svcCtx *svc.ServiceContext) *GameRPCServer {
	return &GameRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *GameRPCServer) Ping(ctx context.Context, in *game.Request) (*game.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
