// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: hallService.proto

package hall

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HallRPC_Ping_FullMethodName = "/hall.HallRPC/Ping"
)

// HallRPCClient is the client API for HallRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HallRPCClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hallRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewHallRPCClient(cc grpc.ClientConnInterface) HallRPCClient {
	return &hallRPCClient{cc}
}

func (c *hallRPCClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HallRPC_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HallRPCServer is the server API for HallRPC service.
// All implementations must embed UnimplementedHallRPCServer
// for forward compatibility.
type HallRPCServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHallRPCServer()
}

// UnimplementedHallRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHallRPCServer struct{}

func (UnimplementedHallRPCServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHallRPCServer) mustEmbedUnimplementedHallRPCServer() {}
func (UnimplementedHallRPCServer) testEmbeddedByValue()                 {}

// UnsafeHallRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HallRPCServer will
// result in compilation errors.
type UnsafeHallRPCServer interface {
	mustEmbedUnimplementedHallRPCServer()
}

func RegisterHallRPCServer(s grpc.ServiceRegistrar, srv HallRPCServer) {
	// If the following call pancis, it indicates UnimplementedHallRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HallRPC_ServiceDesc, srv)
}

func _HallRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HallRPC_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallRPCServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// HallRPC_ServiceDesc is the grpc.ServiceDesc for HallRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HallRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hall.HallRPC",
	HandlerType: (*HallRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _HallRPC_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hallService.proto",
}
