// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: panguService.proto

package pangurpc

import (
	"context"

	"zero-qp/panguService/rpc/pangu"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pangu.Request
	Response = pangu.Response

	PanGuRPC interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPanGuRPC struct {
		cli zrpc.Client
	}
)

func NewPanGuRPC(cli zrpc.Client) PanGuRPC {
	return &defaultPanGuRPC{
		cli: cli,
	}
}

func (m *defaultPanGuRPC) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pangu.NewPanGuRPCClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
