// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: payService.proto

package pay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayRPC_Ping_FullMethodName = "/user.PayRPC/Ping"
)

// PayRPCClient is the client API for PayRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayRPCClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type payRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPayRPCClient(cc grpc.ClientConnInterface) PayRPCClient {
	return &payRPCClient{cc}
}

func (c *payRPCClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PayRPC_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayRPCServer is the server API for PayRPC service.
// All implementations must embed UnimplementedPayRPCServer
// for forward compatibility.
type PayRPCServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPayRPCServer()
}

// UnimplementedPayRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayRPCServer struct{}

func (UnimplementedPayRPCServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPayRPCServer) mustEmbedUnimplementedPayRPCServer() {}
func (UnimplementedPayRPCServer) testEmbeddedByValue()                {}

// UnsafePayRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayRPCServer will
// result in compilation errors.
type UnsafePayRPCServer interface {
	mustEmbedUnimplementedPayRPCServer()
}

func RegisterPayRPCServer(s grpc.ServiceRegistrar, srv PayRPCServer) {
	// If the following call pancis, it indicates UnimplementedPayRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayRPC_ServiceDesc, srv)
}

func _PayRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayRPC_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayRPCServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PayRPC_ServiceDesc is the grpc.ServiceDesc for PayRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.PayRPC",
	HandlerType: (*PayRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PayRPC_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payService.proto",
}
