// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: hallService.proto

package server

import (
	"context"

	"zero-qp/hallService/rpc/hall"
	"zero-qp/hallService/rpc/internal/logic"
	"zero-qp/hallService/rpc/internal/svc"
)

type HallRPCServer struct {
	svcCtx *svc.ServiceContext
	hall.UnimplementedHallRPCServer
}

func NewHallRPCServer(svcCtx *svc.ServiceContext) *HallRPCServer {
	return &HallRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *HallRPCServer) Ping(ctx context.Context, in *hall.Request) (*hall.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
