// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: panguService.proto

package pangu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PanGuRPC_Ping_FullMethodName = "/pangu.PanGuRPC/Ping"
)

// PanGuRPCClient is the client API for PanGuRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanGuRPCClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type panGuRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPanGuRPCClient(cc grpc.ClientConnInterface) PanGuRPCClient {
	return &panGuRPCClient{cc}
}

func (c *panGuRPCClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PanGuRPC_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanGuRPCServer is the server API for PanGuRPC service.
// All implementations must embed UnimplementedPanGuRPCServer
// for forward compatibility.
type PanGuRPCServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPanGuRPCServer()
}

// UnimplementedPanGuRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanGuRPCServer struct{}

func (UnimplementedPanGuRPCServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPanGuRPCServer) mustEmbedUnimplementedPanGuRPCServer() {}
func (UnimplementedPanGuRPCServer) testEmbeddedByValue()                  {}

// UnsafePanGuRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanGuRPCServer will
// result in compilation errors.
type UnsafePanGuRPCServer interface {
	mustEmbedUnimplementedPanGuRPCServer()
}

func RegisterPanGuRPCServer(s grpc.ServiceRegistrar, srv PanGuRPCServer) {
	// If the following call pancis, it indicates UnimplementedPanGuRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PanGuRPC_ServiceDesc, srv)
}

func _PanGuRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanGuRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanGuRPC_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanGuRPCServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PanGuRPC_ServiceDesc is the grpc.ServiceDesc for PanGuRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanGuRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pangu.PanGuRPC",
	HandlerType: (*PanGuRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PanGuRPC_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "panguService.proto",
}
