// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: panguService.proto

package server

import (
	"context"

	"zero-qp/panguService/rpc/internal/logic"
	"zero-qp/panguService/rpc/internal/svc"
	"zero-qp/panguService/rpc/pangu"
)

type PanGuRPCServer struct {
	svcCtx *svc.ServiceContext
	pangu.UnimplementedPanGuRPCServer
}

func NewPanGuRPCServer(svcCtx *svc.ServiceContext) *PanGuRPCServer {
	return &PanGuRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *PanGuRPCServer) Ping(ctx context.Context, in *pangu.Request) (*pangu.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
